spring:
  application:
    name: algoarena

  datasource:
    url: jdbc:postgresql://localhost:5432/algoarena
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      naming:
        #naming strategy for automatic converting (camelCase to snake_case)
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update

  minio:
    url: ${MINIO_ENDPOINT:http://localhost:9000}
    access-key: ${MINIO_ROOT_USER:minioadmin}
    secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}
    bucket-name: ${MINIO_BUCKET_NAME}
    presigned-url-expiry: ${MINIO_PRESIGNED_URL_EXPIRY:5}
